import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

export const serverRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const projectRoot = path.resolve(serverRoot, '..');

// Root scripts and direct server commands always load the same local file.
dotenv.config({ path: path.join(serverRoot, '.env'), quiet: true });

const placeholderPattern = /replace[_ -]|choose[_ -]|change[_ -]?me|your[_ -]|example[_ -]|placeholder/i;

function requiredSecret(value, name) {
  if (typeof value !== 'string' || !value.length || placeholderPattern.test(value)) {
    throw new Error(`${name} must be configured locally and cannot be a placeholder.`);
  }
  return value;
}

function integerSetting(env, name, fallback, min, max) {
  const value = env[name] ?? String(fallback);
  if (!/^\d+$/.test(value) || !Number.isSafeInteger(Number(value)) || Number(value) < min || Number(value) > max) {
    throw new Error(`${name} must be an integer from ${min} to ${max}.`);
  }
  return Number(value);
}

function sessionSecretSetting(value) {
  const secret = requiredSecret(value, 'SESSION_SECRET');
  const isHex = /^[a-f\d]{64,}$/i.test(secret) && secret.length % 2 === 0;
  const isBase64 = /^[A-Za-z\d+/_-]{43,}={0,2}$/.test(secret)
    && Buffer.from(secret, 'base64url').length >= 32;
  if ((!isHex && !isBase64) || new Set(secret).size < 12) {
    throw new Error('SESSION_SECRET must encode at least 32 randomly generated bytes as hex or base64/base64url.');
  }
  return secret;
}

export function loadConfig(env = process.env) {
  const nodeEnv = env.NODE_ENV ?? 'development';
  if (!['development', 'test', 'production'].includes(nodeEnv)) {
    throw new Error('NODE_ENV must be development, test, or production.');
  }
  let origin;
  try {
    origin = new URL(env.APP_ORIGIN ?? 'http://localhost:5173');
  } catch {
    throw new Error('APP_ORIGIN must be an HTTP or HTTPS origin.');
  }
  if (!['http:', 'https:'].includes(origin.protocol) || origin.username || origin.password || origin.pathname !== '/' || origin.search || origin.hash) {
    throw new Error('APP_ORIGIN must be an HTTP or HTTPS origin without a path or credentials.');
  }
  if (env.DB_FILE === ':memory:' || env.DB_FILE?.startsWith('file:')) {
    throw new Error('DB_FILE must be a persistent local filesystem path.');
  }
  const dbFile = path.resolve(serverRoot, env.DB_FILE || './data/challenge_portal.sqlite');
  const uploadDir = path.resolve(serverRoot, env.UPLOAD_DIR || './storage');
  const clientDirectory = path.join(projectRoot, 'client');
  for (const [name, storagePath] of [['DB_FILE', dbFile], ['UPLOAD_DIR', uploadDir]]) {
    const relativeToClient = path.relative(clientDirectory, storagePath);
    if (relativeToClient === '' || (!relativeToClient.startsWith(`..${path.sep}`) && relativeToClient !== '..' && !path.isAbsolute(relativeToClient))) {
      throw new Error(`${name} must be outside the client directory.`);
    }
  }
  return {
    nodeEnv,
    port: integerSetting(env, 'PORT', 3000, 1, 65535),
    appOrigin: origin.origin,
    secureCookies: origin.protocol === 'https:',
    uploadDir,
    dbFile,
    sessionSecret: sessionSecretSetting(env.SESSION_SECRET),
    trustProxy: false,
    loginWindowMs: integerSetting(env, 'LOGIN_WINDOW_MS', 900000, 1000, 86400000),
    loginMax: integerSetting(env, 'LOGIN_MAX', 10, 1, 10000),
    answerWindowMs: integerSetting(env, 'ANSWER_WINDOW_MS', 60000, 1000, 86400000),
    answerMax: integerSetting(env, 'ANSWER_MAX', 20, 1, 10000),
    seedPasswords: {
      admin: env.SEED_ADMIN_PASSWORD,
      user1: env.SEED_USER1_PASSWORD,
      user2: env.SEED_USER2_PASSWORD,
    },
  };
}

export function validateSeedPassword(value, variableName) {
  const password = requiredSecret(value, variableName);
  // Match the API's JavaScript string-length limit so seeded passwords remain
  // usable by the login endpoint, including strings containing surrogate pairs.
  if (password.length < 8 || password.length > 128) {
    throw new Error(`${variableName} must contain 8 to 128 characters.`);
  }
  return password;
}
